/Users/cakelittle/Documents/Developer/DLT_bot/env/bin/python /Users/cakelittle/Documents/Developer/DLT_bot/bot.py
/Users/cakelittle/Documents/Developer/DLT_bot/env/bin/python /Users/cakelittle/Documents/Developer/DLT_bot/bot.py
/Users/cakelittle/Documents/Developer/DLT_bot/env/bin/python /Users/cakelittle/Documents/Developer/DLT_bot/bot.py
/Users/cakelittle/Documents/Developer/DLT_bot/env/bin/python /Users/cakelittle/Documents/Developer/DLT_bot/bot.py
/Users/cakelittle/Documents/Developer/DLT_bot/env/bin/python /Users/cakelittle/Documents/Developer/DLT_bot/bot.py
/Users/cakelittle/Documents/Developer/DLT_bot/env/bin/python /Users/cakelittle/Documents/Developer/DLT_bot/bot.py
/Users/cakelittle/Documents/Developer/DLT_bot/env/bin/python /Users/cakelittle/Documents/Developer/DLT_bot/bot.py
/Users/cakelittle/Documents/Developer/DLT_bot/env/bin/python /Users/cakelittle/Documents/Developer/DLT_bot/bot.py
/Users/cakelittle/Documents/Developer/DLT_bot/env/bin/python /Users/cakelittle/Documents/Developer/DLT_bot/bot.py
/Users/cakelittle/Documents/Developer/DLT_bot/env/bin/python /Users/cakelittle/Documents/Developer/DLT_bot/bot.py